version: '3.7'
services:
  mosquitto:
    image: eclipse-mosquitto:2.0.18
    ports:
      - "1883:1883" # Porta padrão para MQTT
      - "9001:9001" # Porta para MQTT sobre WebSockets
    volumes:
      - ./data/config:/mosquitto/config
      - ./data/data:/mosquitto/data
      - ./data/log:/mosquitto/log
    restart: unless-stopped
  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: iotdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    command:
      -c wal_level=logical
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=password
      - GF_USERS_ALLOW_SIGN_UP=false
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
  connect:
    image: debezium/connect:1.3
    ports:
      - "8083:8083"
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      CONFIG_STORAGE_TOPIC: debezium_server_configs
      OFFSET_STORAGE_TOPIC: debezium_server_offsets
      STATUS_STORAGE_TOPIC: debezium_server_statuses
    depends_on:
      - kafka
      - postgres
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace:cached
    command: sleep infinity
    environment:
      DB_HOST: postgres
      MQTT_BROKER_ADDRESS: mosquitto

volumes:
  postgres_data:
    driver: local
  grafana_data:
    driver: local